package dotty.tools.backend.python

import dotty.tools.backend.python.ir.*

import java.io.PrintWriter

/** Emits Python source code from the Python IR.
  *
  * Walks the IR tree and produces properly indented Python source text.
  */
object PyEmitter:

  def emit(module: PyModule, out: PrintWriter): Unit =
    val e = new Emitter(out)
    e.emitModule(module)

  private class Emitter(out: PrintWriter):
    private var indentLevel = 0
    private val indentStr = "    " // 4 spaces

    private def indent(): Unit = indentLevel += 1
    private def dedent(): Unit = indentLevel -= 1

    private def line(s: String): Unit =
      out.print(indentStr * indentLevel)
      out.println(s)

    private def emptyLine(): Unit = out.println()

    // ─── Module ──────────────────────────────────────────────────

    def emitModule(module: PyModule): Unit =
      line("# Generated by Scala 3 Python backend")
      emptyLine()

      for imp <- module.imports do
        emitImport(imp)
      if module.imports.nonEmpty then emptyLine()

      for d <- module.defs do
        emitTopLevelDef(d)
        emptyLine()

      for s <- module.initStmts do
        emitStmt(s)

    // ─── Imports ─────────────────────────────────────────────────

    private def emitImport(imp: PyImport): Unit = imp match
      case PyImport.Import(module, alias) =>
        val aliasStr = alias.map(a => s" as ${a.value}").getOrElse("")
        line(s"import ${module}$aliasStr")
      case PyImport.FromImport(module, names) =>
        val namesStr = names.map { (name, alias) =>
          alias.map(a => s"${name.value} as ${a.value}").getOrElse(name.value)
        }.mkString(", ")
        line(s"from ${module} import $namesStr")

    // ─── Top-level definitions ───────────────────────────────────

    private def emitTopLevelDef(d: PyTopLevelDef): Unit = d match
      case PyTopLevelDef.TLClassDef(cls) => emitClassDef(cls)
      case PyTopLevelDef.TLFuncDef(func) => emitFuncDef(func)
      case PyTopLevelDef.TLAssign(target, value) =>
        line(s"${target.value} = ${exprToStr(value)}")

    // ─── Class definition ────────────────────────────────────────

    private def emitClassDef(cls: PyClassDef): Unit =
      val basesStr = if cls.bases.isEmpty then "" else s"(${cls.bases.map(exprToStr).mkString(", ")})"
      line(s"class ${cls.name.value}$basesStr:")
      indent()
      if cls.members.isEmpty then
        line("pass")
      else
        for (member, idx) <- cls.members.zipWithIndex do
          emitClassMember(member)
          if idx < cls.members.length - 1 then emptyLine()
      dedent()

    private def emitClassMember(member: PyClassMember): Unit = member match
      case PyClassMember.Method(func, decorators) =>
        for d <- decorators do emitDecorator(d)
        emitFuncDef(func)
      case PyClassMember.FieldInit(target, value) =>
        line(s"${exprToStr(target)} = ${exprToStr(value)}")
      case PyClassMember.NestedClass(cls) =>
        emitClassDef(cls)
      case PyClassMember.Stmt(stmt) =>
        emitStmt(stmt)
      case PyClassMember.Pass =>
        line("pass")

    private def emitDecorator(d: PyDecorator): Unit = d match
      case PyDecorator.StaticMethod => line("@staticmethod")
      case PyDecorator.ClassMethod  => line("@classmethod")
      case PyDecorator.Property     => line("@property")
      case PyDecorator.Custom(expr) => line(s"@${exprToStr(expr)}")

    // ─── Function definition ─────────────────────────────────────

    private def emitFuncDef(func: PyFuncDef): Unit =
      val paramsStr = func.params.map(paramToStr).mkString(", ")
      val retStr = func.returnType.map(t => s" -> ${typeAnnotToStr(t)}").getOrElse("")
      line(s"def ${func.name.value}($paramsStr)$retStr:")
      indent()
      if func.body.isEmpty then line("pass")
      else func.body.foreach(emitStmt)
      dedent()

    private def paramToStr(p: PyParam): String =
      val annot = p.typeAnnot.map(t => s": ${typeAnnotToStr(t)}").getOrElse("")
      val default = p.default.map(d => s" = ${exprToStr(d)}").getOrElse("")
      s"${p.name.value}$annot$default"

    // ─── Statements ──────────────────────────────────────────────

    private def emitStmt(stmt: PyStmt): Unit = stmt match
      case PyStmt.ExprStmt(expr) =>
        line(exprToStr(expr))

      case PyStmt.Assign(target, value) =>
        line(s"${exprToStr(target)} = ${exprToStr(value)}")

      case PyStmt.AugAssign(target, op, value) =>
        line(s"${exprToStr(target)} ${binOpToStr(op)}= ${exprToStr(value)}")

      case PyStmt.Return(Some(value)) =>
        line(s"return ${exprToStr(value)}")
      case PyStmt.Return(None) =>
        line("return")

      case PyStmt.If(cond, body, elifs, elseBody) =>
        line(s"if ${exprToStr(cond)}:")
        indent(); body.foreach(emitStmt); dedent()
        for (elifCond, elifBody) <- elifs do
          line(s"elif ${exprToStr(elifCond)}:")
          indent(); elifBody.foreach(emitStmt); dedent()
        elseBody.foreach { eb =>
          line("else:")
          indent(); eb.foreach(emitStmt); dedent()
        }

      case PyStmt.While(cond, body) =>
        line(s"while ${exprToStr(cond)}:")
        indent(); body.foreach(emitStmt); dedent()

      case PyStmt.For(target, iter, body) =>
        line(s"for ${exprToStr(target)} in ${exprToStr(iter)}:")
        indent(); body.foreach(emitStmt); dedent()

      case PyStmt.Try(body, handlers, elseBody, finallyBody) =>
        line("try:")
        indent(); body.foreach(emitStmt); dedent()
        for h <- handlers do
          val typeStr = h.exnType.map(exprToStr).getOrElse("")
          val nameStr = h.name.map(n => s" as ${n.value}").getOrElse("")
          val excStr = if typeStr.isEmpty && nameStr.isEmpty then "" else s" ${typeStr}${nameStr}"
          line(s"except$excStr:")
          indent(); h.body.foreach(emitStmt); dedent()
        elseBody.foreach { eb =>
          line("else:")
          indent(); eb.foreach(emitStmt); dedent()
        }
        finallyBody.foreach { fb =>
          line("finally:")
          indent(); fb.foreach(emitStmt); dedent()
        }

      case PyStmt.Raise(Some(exc)) =>
        line(s"raise ${exprToStr(exc)}")
      case PyStmt.Raise(None) =>
        line("raise")

      case PyStmt.Assert(test, Some(msg)) =>
        line(s"assert ${exprToStr(test)}, ${exprToStr(msg)}")
      case PyStmt.Assert(test, None) =>
        line(s"assert ${exprToStr(test)}")

      case PyStmt.Pass    => line("pass")
      case PyStmt.Break   => line("break")
      case PyStmt.Continue => line("continue")

      case PyStmt.Del(target) =>
        line(s"del ${exprToStr(target)}")

      case PyStmt.VarDef(name, tpe, _, rhs) =>
        val annot = tpe.map(t => s": ${typeAnnotToStr(t)}").getOrElse("")
        line(s"${name.value}$annot = ${exprToStr(rhs)}")

      case PyStmt.Block(stmts) =>
        stmts.foreach(emitStmt)

      case PyStmt.Labeled(label, body) =>
        // Emit as try/except for non-local return
        line("try:")
        indent(); body.foreach(emitStmt); dedent()
        line(s"except _NonLocalReturn_${label.value} as _nlr:")
        indent(); line("return _nlr.value"); dedent()

      case PyStmt.LabelReturn(label, value) =>
        line(s"raise _NonLocalReturn_${label.value}(${exprToStr(value)})")

      case PyStmt.FuncDefStmt(func) =>
        emitFuncDef(func)

      case PyStmt.ClassDefStmt(cls) =>
        emitClassDef(cls)

    // ─── Expressions (to string) ─────────────────────────────────

    private def exprToStr(expr: PyExpr): String = expr match
      case PyExpr.NoneLit       => "None"
      case PyExpr.BoolLit(true) => "True"
      case PyExpr.BoolLit(false) => "False"
      case PyExpr.IntLit(v)     => v.toString
      case PyExpr.FloatLit(v)   => v.toString
      case PyExpr.StringLit(v)  => s"\"${escapeString(v)}\""

      case PyExpr.Name(name) => name.value
      case PyExpr.QualRef(qual) => qual.toString
      case PyExpr.Attr(obj, name) => s"${parenthesize(obj)}.${name.value}"
      case PyExpr.Subscript(obj, index) => s"${parenthesize(obj)}[${exprToStr(index)}]"

      case PyExpr.Call(func, args) =>
        s"${parenthesize(func)}(${args.map(exprToStr).mkString(", ")})"

      case PyExpr.New(cls, args) =>
        s"${exprToStr(cls)}(${args.map(exprToStr).mkString(", ")})"

      case PyExpr.BinOp(op, lhs, rhs) =>
        s"(${exprToStr(lhs)} ${binOpToStr(op)} ${exprToStr(rhs)})"

      case PyExpr.UnaryOp(op, operand) =>
        s"${unaryOpToStr(op)}${parenthesize(operand)}"

      case PyExpr.BoolOp(op, values) =>
        val opStr = op match
          case PyBoolOp.And => " and "
          case PyBoolOp.Or  => " or "
        s"(${values.map(exprToStr).mkString(opStr)})"

      case PyExpr.Compare(left, ops, rights) =>
        val pairs = ops.zip(rights).map { (op, right) =>
          s"${cmpOpToStr(op)} ${exprToStr(right)}"
        }
        s"(${exprToStr(left)} ${pairs.mkString(" ")})"

      case PyExpr.IfExpr(cond, thenE, elseE) =>
        s"(${exprToStr(thenE)} if ${exprToStr(cond)} else ${exprToStr(elseE)})"

      case PyExpr.Lambda(params, body) =>
        s"lambda ${params.map(paramToStr).mkString(", ")}: ${exprToStr(body)}"

      case PyExpr.TupleLit(elems) =>
        if elems.length == 1 then s"(${exprToStr(elems.head)},)"
        else s"(${elems.map(exprToStr).mkString(", ")})"

      case PyExpr.ListLit(elems) =>
        s"[${elems.map(exprToStr).mkString(", ")}]"

      case PyExpr.DictLit(keys, values) =>
        val pairs = keys.zip(values).map { (k, v) =>
          s"${exprToStr(k)}: ${exprToStr(v)}"
        }
        s"{${pairs.mkString(", ")}}"

      case PyExpr.IsInstance(obj, cls) =>
        s"isinstance(${exprToStr(obj)}, ${exprToStr(cls)})"

      case PyExpr.Cast(obj, _) =>
        exprToStr(obj) // no-op in Python

      case PyExpr.LoadModule(qualName) =>
        s"${qualName.parts.last}_MODULE"

      case PyExpr.SuperRef(_, parentClass) =>
        parentClass match
          case None    => "super()"
          case Some(p) => exprToStr(p)

      case PyExpr.This => "self"

      case PyExpr.IntWrap32(e)  => s"_rt_i32(${exprToStr(e)})"
      case PyExpr.IntWrap64(e)  => s"_rt_i64(${exprToStr(e)})"
      case PyExpr.FloatWrap(e)  => s"_rt_f32(${exprToStr(e)})"

      case PyExpr.StringConcat(parts) =>
        parts.map { p =>
          p match
            case PyExpr.StringLit(_) => exprToStr(p)
            case _ => s"str(${exprToStr(p)})"
        }.mkString(" + ")

      case PyExpr.NewArray(length, init) =>
        s"[${exprToStr(init)}] * ${exprToStr(length)}"

      case PyExpr.ArrayLit(elems) =>
        s"[${elems.map(exprToStr).mkString(", ")}]"

      case PyExpr.ArraySelect(array, index) =>
        s"${parenthesize(array)}[${exprToStr(index)}]"

      case PyExpr.ArrayLength(array) =>
        s"len(${exprToStr(array)})"

      case PyExpr.WrapThrowable(e) =>
        exprToStr(e) // simplified for now
      case PyExpr.UnwrapThrowable(e) =>
        exprToStr(e) // simplified for now

    private def parenthesize(expr: PyExpr): String = expr match
      case PyExpr.BinOp(_, _, _) | PyExpr.BoolOp(_, _) | PyExpr.Compare(_, _, _) |
           PyExpr.IfExpr(_, _, _) | PyExpr.Lambda(_, _) | PyExpr.UnaryOp(_, _) =>
        s"(${exprToStr(expr)})"
      case _ =>
        exprToStr(expr)

    // ─── Operator strings ────────────────────────────────────────

    private def binOpToStr(op: PyBinOp): String = op match
      case PyBinOp.Add      => "+"
      case PyBinOp.Sub      => "-"
      case PyBinOp.Mul      => "*"
      case PyBinOp.Div      => "/"
      case PyBinOp.FloorDiv => "//"
      case PyBinOp.Mod      => "%"
      case PyBinOp.Pow      => "**"
      case PyBinOp.BitOr    => "|"
      case PyBinOp.BitAnd   => "&"
      case PyBinOp.BitXor   => "^"
      case PyBinOp.LShift   => "<<"
      case PyBinOp.RShift   => ">>"

    private def unaryOpToStr(op: PyUnaryOp): String = op match
      case PyUnaryOp.Not    => "not "
      case PyUnaryOp.Neg    => "-"
      case PyUnaryOp.Pos    => "+"
      case PyUnaryOp.Invert => "~"

    private def cmpOpToStr(op: PyCmpOp): String = op match
      case PyCmpOp.Eq    => "=="
      case PyCmpOp.NotEq => "!="
      case PyCmpOp.Lt    => "<"
      case PyCmpOp.LtE   => "<="
      case PyCmpOp.Gt    => ">"
      case PyCmpOp.GtE   => ">="
      case PyCmpOp.Is    => "is"
      case PyCmpOp.IsNot => "is not"

    // ─── Type annotations ────────────────────────────────────────

    private def typeAnnotToStr(t: PyTypeAnnot): String = t match
      case PyTypeAnnot.Named(name)       => name
      case PyTypeAnnot.Qualified(qual)   => qual.toString
      case PyTypeAnnot.Parameterized(base, args) =>
        s"${typeAnnotToStr(base)}[${args.map(typeAnnotToStr).mkString(", ")}]"
      case PyTypeAnnot.Union(members) =>
        members.map(typeAnnotToStr).mkString(" | ")
      case PyTypeAnnot.Optional(inner) =>
        s"${typeAnnotToStr(inner)} | None"
      case PyTypeAnnot.Any => "Any"

    // ─── Utilities ───────────────────────────────────────────────

    private def escapeString(s: String): String =
      s.replace("\\", "\\\\")
       .replace("\"", "\\\"")
       .replace("\n", "\\n")
       .replace("\r", "\\r")
       .replace("\t", "\\t")
