package dotty.tools.backend.python

import dotty.tools.backend.python.ir.pyir.*

import java.io.PrintWriter
import scala.collection.mutable

/** Emits Python source text from a list of `PyClassDef`s.
 *
 *  Consumes the typed PyIR and produces a single bundled Python file
 *  with an inline runtime preamble. Called from `GenPython.linkAndWrite`.
 *
 *  Responsibilities:
 *    - `@staticmethod` decoration driven by `PyMemberFlags.namespace`
 *    - `self` parameter insertion for instance methods
 *    - Module-singleton instantiation for `PyClassKind.ModuleClass`
 *    - Main-guard synthesis from a `(PyClassName, PyClassKind)` entry
 *      - looks up the actual `main` method by simple name and invokes
 *      it with the correct encoded signature
 *    - Float NaN/Inf literal fix (`float('nan')` / `float('inf')`)
 *    - Control-character string escaping
 *    - Fully-qualified module variable names (no cross-package
 *      module-name collision)
 *    - Mechanical numeric wrapping (`_scpy_i32` / `_scpy_i64` /
 *      `_scpy_f32`) driven by the op code
 *    - `PyMatch` lowering to nested `if/elif` (stmt) or ternary (expr)
 */
object PyIREmitter:

  /** Reserved prefix for compiler-invented Python identifiers. */
  val Prefix: String = "_scpy_"

  /** Entry point for a "main" method: the class where it lives plus
   *  that class's kind (Class vs ModuleClass - determines whether the
   *  guard calls `Name.main(...)` or `_scpy_mod_Name.main(...)`). */
  type MainEntry = (PyClassName, PyClassKind)

  private sealed trait ExternImport
  private final case class ModuleImport(module: String) extends ExternImport
  private final case class FromImport(module: String, name: String) extends ExternImport

  /** Emit a bundle: runtime preamble + all classes + optional main
   *  entry point, into the given writer.
   *
   *  When `mainEntry` is provided, the emitter looks up a method named
   *  `main` (by simple name) on the given class and synthesizes an
   *  `if __name__ == "__main__":` guard calling it with `sys.argv[1:]`
   *  iff it takes any parameters.
   */
  def emit(
      classes:   List[PyClassDef],
      mainEntry: Option[MainEntry],
      out:       PrintWriter
  ): Unit =
    val e = new Emitter(out)
    e.emitBundle(classes, mainEntry)

  /** Convenience for producing the Python source as a `String`. */
  def emitToString(
      classes:   List[PyClassDef],
      mainEntry: Option[MainEntry]
  ): String =
    val buf = new java.io.StringWriter()
    val pw  = new PrintWriter(buf)
    try emit(classes, mainEntry, pw)
    finally pw.flush()
    buf.toString

  // ===============================================================
  //  Private emitter state machine
  // ===============================================================

  private class Emitter(out: PrintWriter):
    private var indentLevel: Int = 0
    private val indentStr: String = "    "
    private val externAliases = mutable.LinkedHashMap.empty[ExternImport, String]

    private def indent(): Unit = indentLevel += 1
    private def dedent(): Unit = indentLevel -= 1

    private def line(s: String): Unit =
      if s.isEmpty then out.println()
      else
        out.print(indentStr * indentLevel)
        out.println(s)

    private def emptyLine(): Unit = out.println()

    // -- Entry point ---------------------------------------------

    def emitBundle(classes: List[PyClassDef], mainEntry: Option[MainEntry]): Unit =
      collectExternAliases(classes)

      line("# Generated by Scala 3 Python backend (PyIR)")
      emptyLine()

      // Runtime preamble - defines numeric wrappers, Predef, etc.
      out.print(PyIRRuntime.content)
      emptyLine()

      emitExternImports()
      if externAliases.nonEmpty then
        emptyLine()

      // Class definitions + module-singleton initializers
      for cls <- classes do
        line(s"# -- ${cls.name.nameString} --")
        emptyLine()
        emitClassDef(cls)
        emptyLine()
        if cls.kind == PyClassKind.ModuleClass then
          emitModuleSingletonInit(cls)
          emptyLine()

      mainEntry.foreach(entry => emitMainGuard(entry, classes))

    // -- Class definition ----------------------------------------

    private def emitClassDef(cls: PyClassDef): Unit =
      val bases = buildBasesList(cls)
      val basesStr = if bases.isEmpty then "" else s"(${bases.mkString(", ")})"
      line(s"class ${classIdentifier(cls.name)}$basesStr:")
      indent()

      val hasConstructor = cls.methods.exists(_.flags.namespace == PyMemberNamespace.Constructor)
      val needsSyntheticInit = !hasConstructor && cls.fields.nonEmpty

      var first = true
      def spacer(): Unit =
        if first then first = false else emptyLine()

      // Emit constructor (if any) or synthesize a field-init __init__
      if hasConstructor then
        val ctor = cls.methods.find(_.flags.namespace == PyMemberNamespace.Constructor).get
        spacer()
        emitMethodDef(cls, ctor)
      else if needsSyntheticInit then
        spacer()
        emitSyntheticInit(cls)

      // Emit the remaining (non-constructor) methods
      for m <- cls.methods if m.flags.namespace != PyMemberNamespace.Constructor do
        spacer()
        emitMethodDef(cls, m)

      // If the class has no members at all, emit `pass`
      if first then line("pass")

      dedent()

    private def buildBasesList(cls: PyClassDef): List[String] =
      val superPart =
        cls.superClass.toList.filterNot(_ == PyClassName.ObjectClass).map(classIdentifier)
      val interfacePart = cls.interfaces.map(classIdentifier)
      superPart ++ interfacePart

    private def emitSyntheticInit(cls: PyClassDef): Unit =
      line("def __init__(self) -> None:")
      indent()
      if cls.fields.isEmpty then
        line("pass")
      else
        for f <- cls.fields do
          line(s"self.${f.name.simple.name} = None")
      dedent()

    // -- Method definition ---------------------------------------

    private def emitMethodDef(cls: PyClassDef, method: PyMethodDef): Unit =
      // Decorator for static methods
      if method.flags.namespace == PyMemberNamespace.PublicStatic
         || method.flags.namespace == PyMemberNamespace.PrivateStatic then
        line("@staticmethod")

      val methodPyName = method.name.encoded
      val paramsList   = buildParamList(method)
      val retAnnot     = pythonReturnAnnot(method.resultType)
      line(s"def $methodPyName($paramsList)$retAnnot:")

      indent()
      method.body match
        case None =>
          line("raise NotImplementedError()")
        case Some(body) =>
          val stmts = flattenBlock(body)
          val isVoidReturn = method.resultType == PyVoidType
                          || method.resultType == PyNothingType
                          || method.flags.namespace == PyMemberNamespace.Constructor
          emitMethodBody(stmts, returnLast = !isVoidReturn)
      dedent()

    private def buildParamList(method: PyMethodDef): String =
      val selfParam: List[String] =
        if method.flags.namespace.isInstance
           || method.flags.namespace == PyMemberNamespace.Constructor
        then List("self")
        else Nil
      val userParams = method.args.map { p =>
        val annot = pythonTypeAnnot(p.ptpe) match
          case ""    => ""
          case "Any" => ""
          case a     => s": $a"
        s"${p.name.name}$annot"
      }
      (selfParam ++ userParams).mkString(", ")

    private def pythonReturnAnnot(t: PyType): String =
      pythonTypeAnnot(t) match
        case ""    => ""
        case "Any" => ""  // skip noisy untyped annotation
        case s     => s" -> $s"

    private def pythonTypeAnnot(t: PyType): String = t match
      case PyVoidType | PyNothingType | PyNullType => "None"
      case PyBooleanType => "bool"
      case PyCharType | PyByteType | PyShortType | PyIntType | PyLongType => "int"
      case PyFloatType | PyDoubleType => "float"
      case PyStringType => "str"
      case PyArrayType  => "list"
      // Drop class-type annotations - they would be forward references
      // to identifiers the class/module is still in the middle of defining.
      case PyClassType(_) => ""
      case PyAnyType | PyUndefinedType => ""

    private def emitMethodBody(stmts: List[PyTree], returnLast: Boolean): Unit =
      if stmts.isEmpty then
        line("pass")
      else if !returnLast then
        stmts.foreach(emitStmt)
      else
        for s <- stmts.init do emitStmt(s)
        wrapLastReturn(stmts.last)

    /** Turn the last statement of a method body into a `return`. For
     *  nested structures (blocks, if/else, try/catch), recurse into
     *  every exit path so each one is wrapped. */
    private def wrapLastReturn(tree: PyTree): Unit = tree match
      case PyBlock(stats, expr) =>
        stats.foreach(emitStmt)
        wrapLastReturn(expr)

      case PyIf(cond, thenp, elsep) =>
        line(s"if ${exprToStr(cond)}:")
        indent(); wrapLastReturn(thenp); dedent()
        val elseStmts = flattenBlock(elsep)
        if elseStmts.nonEmpty then
          line("else:")
          indent(); wrapLastReturn(elsep); dedent()

      case PyTryCatch(block, errVar, _, handler) =>
        line("try:")
        indent(); wrapLastReturn(block); dedent()
        line(s"except Exception as ${errVar.name}:")
        indent(); wrapLastReturn(handler); dedent()

      case PyTryFinally(block, finalizer) =>
        line("try:")
        indent(); wrapLastReturn(block); dedent()
        line("finally:")
        indent(); emitBlockStmts(finalizer); dedent()

      case PyMatch(selector, cases, default) =>
        val selStr = exprToStr(selector)
        if cases.isEmpty then
          wrapLastReturn(default)
        else
          var first = true
          for (lits, body) <- cases do
            val keyword = if first then "if" else "elif"
            first = false
            val conds = lits.map(lit => s"$selStr == ${exprToStr(lit)}").mkString(" or ")
            line(s"$keyword $conds:")
            indent(); wrapLastReturn(body); dedent()
          line("else:")
          indent(); wrapLastReturn(default); dedent()

      case _: PyUnitLit =>
        line("return None")

      case _ if tree.tpe == PyVoidType || tree.tpe == PyNothingType =>
        emitStmt(tree)

      case _ =>
        line(s"return ${exprToStr(tree)}")

    // -- Statements ----------------------------------------------

    private def emitStmt(tree: PyTree): Unit = tree match
      case PyVarDef(name, _, _, _, rhs) =>
        line(s"${name.name} = ${exprToStr(rhs)}")

      case PyAssign(lhs, rhs) =>
        line(s"${exprToStr(lhs)} = ${exprToStr(rhs)}")

      case PyReturn(value) =>
        value match
          case _: PyUnitLit => line("return")
          case _            => line(s"return ${exprToStr(value)}")

      case PyWhile(cond, body) =>
        line(s"while ${exprToStr(cond)}:")
        indent()
        emitBlockStmts(body)
        dedent()

      case PyForEach(varName, iter, body) =>
        line(s"for ${varName.name} in ${exprToStr(iter)}:")
        indent()
        emitBlockStmts(body)
        dedent()

      case PySkip() =>
        line("pass")

      case PyBlock(stats, expr) =>
        stats.foreach(emitStmt)
        emitStmt(expr)

      case PyIf(cond, thenp, elsep) =>
        line(s"if ${exprToStr(cond)}:")
        indent()
        emitBlockStmts(thenp)
        dedent()
        val elseStmts = flattenBlock(elsep)
        if elseStmts.nonEmpty then
          line("else:")
          indent()
          elseStmts.foreach(emitStmt)
          dedent()

      case PyTryCatch(block, errVar, _, handler) =>
        line("try:")
        indent()
        emitBlockStmts(block)
        dedent()
        line(s"except Exception as ${errVar.name}:")
        indent()
        emitBlockStmts(handler)
        dedent()

      case PyTryFinally(block, finalizer) =>
        line("try:")
        indent()
        emitBlockStmts(block)
        dedent()
        line("finally:")
        indent()
        emitBlockStmts(finalizer)
        dedent()

      case PyLabeled(_, body) =>
        // Placeholder - label/break lowering is not yet implemented
        emitBlockStmts(body)

      case PyLabelReturn(_, value) =>
        line(s"return ${exprToStr(value)}")

      case PyMatch(selector, cases, default) =>
        val selStr = exprToStr(selector)
        if cases.isEmpty then
          emitBlockStmts(default)
        else
          var first = true
          for (lits, body) <- cases do
            val keyword = if first then "if" else "elif"
            first = false
            val conds = lits.map(lit => s"$selStr == ${exprToStr(lit)}").mkString(" or ")
            line(s"$keyword $conds:")
            indent(); emitBlockStmts(body); dedent()
          val defaultStmts = flattenBlock(default)
          if defaultStmts.nonEmpty then
            line("else:")
            indent(); defaultStmts.foreach(emitStmt); dedent()

      case _: PyUnitLit =>
        ()  // unit in statement position is a no-op

      case expr =>
        // Fall-through: expression used as a statement
        line(exprToStr(expr))

    /** Flatten a tree into a list of statements and emit them. */
    private def emitBlockStmts(tree: PyTree): Unit =
      val stmts = flattenBlock(tree)
      if stmts.isEmpty then line("pass")
      else stmts.foreach(emitStmt)

    private def bindExternAlias(imp: ExternImport): String =
      externAliases.getOrElseUpdate(imp, {
        val raw = imp match
          case ModuleImport(module)    => module
          case FromImport(module, name) => s"${module}_${name}"
        s"${Prefix}ext_${raw.replace('.', '_')}"
      })

    private def importOf(module: String, path: List[String]): (ExternImport, List[String]) =
      if path.isEmpty then (ModuleImport(module), Nil)
      else (FromImport(module, path.head), path.tail)

    private def collectExternAliases(classes: List[PyClassDef]): Unit =
      for
        cls <- classes
        method <- cls.methods
        body <- method.body
      do collectExternAliases(body)

    private def collectExternAliases(tree: PyTree): Unit = tree match
      case tree: PyVarDef =>
        collectExternAliases(tree.rhs)
      case tree: PyAssign =>
        collectExternAliases(tree.lhs)
        collectExternAliases(tree.rhs)
      case tree: PyReturn =>
        collectExternAliases(tree.value)
      case tree: PyWhile =>
        collectExternAliases(tree.cond)
        collectExternAliases(tree.body)
      case tree: PyForEach =>
        collectExternAliases(tree.iterable)
        collectExternAliases(tree.body)
      case _: PySkip =>
        ()
      case tree: PyIf =>
        collectExternAliases(tree.cond)
        collectExternAliases(tree.thenp)
        collectExternAliases(tree.elsep)
      case tree: PyTryCatch =>
        collectExternAliases(tree.block)
        collectExternAliases(tree.handler)
      case tree: PyTryFinally =>
        collectExternAliases(tree.block)
        collectExternAliases(tree.finalizer)
      case tree: PyMatch =>
        collectExternAliases(tree.selector)
        tree.cases.foreach { case (_, body) => collectExternAliases(body) }
        collectExternAliases(tree.default)
      case tree: PyBlock =>
        tree.stats.foreach(collectExternAliases)
        collectExternAliases(tree.expr)
      case tree: PyLabeled =>
        collectExternAliases(tree.body)
      case tree: PyLabelReturn =>
        collectExternAliases(tree.value)
      case _: PyVarRef | _: PyThis | _: PySelectStatic | _: PyLiteral | _: PyClassOf | _: PyLoadModule =>
        ()
      case tree: PySelect =>
        collectExternAliases(tree.qualifier)
      case tree: PyApply =>
        collectExternAliases(tree.receiver)
        tree.args.foreach(collectExternAliases)
      case tree: PyApplyStatically =>
        collectExternAliases(tree.receiver)
        tree.args.foreach(collectExternAliases)
      case tree: PyApplyStatic =>
        tree.args.foreach(collectExternAliases)
      case tree: PyApplyExternal =>
        tree.args.foreach(collectExternAliases)
      case tree: PyExternalRef =>
        val (imp, _) = importOf(tree.module, tree.path)
        bindExternAlias(imp)
      case tree: PyApplyDynamic =>
        collectExternAliases(tree.callee)
        tree.args.foreach(collectExternAliases)
        tree.kwargs.foreach((_, value) => collectExternAliases(value))
      case tree: PyAttrAccess =>
        collectExternAliases(tree.obj)
      case tree: PyNew =>
        tree.args.foreach(collectExternAliases)
      case tree: PyIsInstanceOf =>
        collectExternAliases(tree.expr)
      case tree: PyAsInstanceOf =>
        collectExternAliases(tree.expr)
      case tree: PyNewArray =>
        collectExternAliases(tree.length)
      case tree: PyArrayValue =>
        tree.elems.foreach(collectExternAliases)
      case tree: PyArraySelect =>
        collectExternAliases(tree.array)
        collectExternAliases(tree.index)
      case tree: PyUnaryOp =>
        collectExternAliases(tree.lhs)
      case tree: PyBinaryOp =>
        collectExternAliases(tree.lhs)
        collectExternAliases(tree.rhs)
      case tree: PyClosure =>
        tree.captureValues.foreach(collectExternAliases)
        collectExternAliases(tree.body)

    private def emitExternImports(): Unit =
      for (imp, alias) <- externAliases do
        imp match
          case ModuleImport(module) =>
            line(s"import $module as $alias")
          case FromImport(module, name) =>
            line(s"from $module import $name as $alias")

    // -- Expressions ---------------------------------------------

    private def exprToStr(tree: PyTree): String = tree match
      // Literals
      case PyBooleanLit(true)  => "True"
      case PyBooleanLit(false) => "False"
      case PyCharLit(c)        => c.toInt.toString
      case PyByteLit(v)        => v.toString
      case PyShortLit(v)       => v.toString
      case PyIntLit(v)         => v.toString
      case PyLongLit(v)        => v.toString
      case PyFloatLit(v)       => formatFloat(v)
      case PyDoubleLit(v)      => formatDouble(v)
      case PyStringLit(v)      => "\"" + escapeString(v) + "\""
      case PyNullLit()         => "None"
      case PyUnitLit()         => "None"

      // References
      case PyVarRef(name)      => name.name
      case PyThis()            => "self"
      case PySelect(qual, field) =>
        s"${parenthesize(qual)}.${field.simple.name}"
      case PySelectStatic(field) =>
        s"${classIdentifier(field.owner)}.${field.simple.name}"

      // Calls
      case PyApply(_, receiver, _, method, args) =>
        val argsStr = args.map(exprToStr).mkString(", ")
        s"${parenthesize(receiver)}.${method.encoded}($argsStr)"

      case PyApplyStatically(_, receiver, className, method, args) =>
        val argsStr = args.map(exprToStr).mkString(", ")
        receiver match
          case _: PyThis =>
            s"super().${method.encoded}($argsStr)"
          case _ =>
            val prefix = parenthesize(receiver)
            val sep    = if args.isEmpty then "" else ", "
            s"${classIdentifier(className)}.${method.encoded}($prefix$sep$argsStr)"

      case PyApplyStatic(_, className, method, args) =>
        val argsStr = args.map(exprToStr).mkString(", ")
        s"${moduleVarName(className)}.${method.encoded}($argsStr)"

      case PyApplyExternal(callee, args) =>
        val argsStr = args.map(exprToStr).mkString(", ")
        s"${callee.name}($argsStr)"

      case PyExternalRef(module, path) =>
        val (imp, rest) = importOf(module, path)
        val alias = bindExternAlias(imp)
        if rest.isEmpty then alias
        else s"$alias.${rest.mkString(".")}"

      case PyApplyDynamic(callee, args, kwargs) =>
        val posArgs = args.map(exprToStr)
        val kwArgs = kwargs.map((name, value) => s"$name=${exprToStr(value)}")
        s"${parenthesize(callee)}(${(posArgs ++ kwArgs).mkString(", ")})"

      case PyAttrAccess(obj, name) =>
        s"${parenthesize(obj)}.$name"

      // Construction
      case PyNew(className, _, args) =>
        val argsStr = args.map(exprToStr).mkString(", ")
        s"${classIdentifier(className)}($argsStr)"

      case PyLoadModule(className) =>
        moduleVarName(className)

      // Type tests / casts
      case PyIsInstanceOf(expr, testType) =>
        val cls = testType match
          case PyClassRef(cn) => classIdentifier(cn)
          case PyArrayRef(_, _) => "list"
          case _ => "object"
        s"isinstance(${exprToStr(expr)}, $cls)"

      case PyAsInstanceOf(expr, _) =>
        exprToStr(expr)  // Python is duck-typed, cast is a no-op

      // Arrays
      case PyNewArray(_, length) =>
        s"[None] * ${parenthesize(length)}"

      case PyArrayValue(_, elems) =>
        s"[${elems.map(exprToStr).mkString(", ")}]"

      case PyArraySelect(array, index) =>
        s"${parenthesize(array)}[${exprToStr(index)}]"

      // Operators
      case PyUnaryOp(op, lhs) =>
        emitUnary(op, lhs)

      case PyBinaryOp(op, lhs, rhs) =>
        emitBinary(op, lhs, rhs)

      // Closures (simplified)
      case PyClosure(_, params, _, body, _) =>
        val paramsStr = params.map(_.name.name).mkString(", ")
        s"(lambda $paramsStr: ${exprToStr(body)})"

      case PyClassOf(typeRef) =>
        "\"" + typeRef.encoded + "\""

      // If-expression
      case PyIf(cond, thenp, elsep) =>
        s"(${exprToStr(thenp)} if ${exprToStr(cond)} else ${exprToStr(elsep)})"

      // Block-expression - fall back to final expression (side effects
      // won't be captured; this is a known limitation of the shell
      // emitter).
      case PyBlock(_, expr) =>
        exprToStr(expr)

      case PyMatch(selector, cases, default) =>
        // Lower to nested ternary: each case is `body if cond else <else>`
        val selStr = exprToStr(selector)
        cases.foldRight(exprToStr(default)) { case ((lits, body), elsePart) =>
          val conds = lits.map(lit => s"$selStr == ${exprToStr(lit)}").mkString(" or ")
          s"(${exprToStr(body)} if ($conds) else $elsePart)"
        }

      case PyLabeled(_, body)      => exprToStr(body)
      case PyLabelReturn(_, value) => exprToStr(value)
      case PyTryCatch(block, _, _, _) => exprToStr(block)
      case PyTryFinally(block, _)     => exprToStr(block)

      case other =>
        s"None  # TODO: ${other.getClass.getSimpleName}"

    /** Wrap an expression in parentheses if its precedence requires it. */
    private def parenthesize(tree: PyTree): String = tree match
      case _: PyBinaryOp | _: PyUnaryOp | _: PyIf | _: PyClosure =>
        s"(${exprToStr(tree)})"
      case _ =>
        exprToStr(tree)

    // -- Unary / binary op rendering -----------------------------

    private def emitUnary(op: PyUnaryCode, lhs: PyTree): String =
      import PyUnaryCode.*
      val l = parenthesize(lhs)
      op match
        case BoolNot      => s"(not $l)"
        case IntNeg       => wrapI32(s"-$l")
        case LongNeg      => wrapI64(s"-$l")
        case FloatNeg     => wrapF32(s"-$l")
        case DoubleNeg    => s"(-$l)"
        case IntNot       => wrapI32(s"~$l")
        case LongNot      => wrapI64(s"~$l")

        case CharToInt | ByteToInt | ShortToInt | IntToLong => l
        case LongToInt => wrapI32(l)
        case IntToFloat | LongToFloat | DoubleToFloat => wrapF32(s"float($l)")
        case IntToDouble | LongToDouble | FloatToDouble => s"float($l)"
        case IntToChar  => s"(($l) & 0xFFFF)"
        case IntToByte  => s"((($l) & 0xFF) ^ 0x80) - 0x80"
        case IntToShort => s"((($l) & 0xFFFF) ^ 0x8000) - 0x8000"
        case FloatToInt | DoubleToInt => wrapI32(s"int($l)")
        case FloatToLong | DoubleToLong => wrapI64(s"int($l)")

        case StringLength   => s"len($l)"
        case ArrayLength    => s"len($l)"
        case CheckNotNull   => l
        case GetClass       => s"type($l)"
        case IdentityHashCode => s"id($l)"
        case Clone          => l

        case WrapAsThrowable | UnwrapFromThrowable => l
        case Throw          => s"(lambda: (_ for _ in ()).throw($l))()"

        case FloatToBits | FloatFromBits | DoubleToBits | DoubleFromBits => l

        case ClassGetName      => s"$l.__name__"
        case ClassIsPrimitive  => "False"
        case ClassIsInterface  => "False"
        case ClassIsArray      => s"isinstance($l, list)"

    private def emitBinary(op: PyBinaryCode, lhs: PyTree, rhs: PyTree): String =
      import PyBinaryCode.*
      val l = parenthesize(lhs)
      val r = parenthesize(rhs)
      op match
        // Boolean
        case BoolEq => s"($l == $r)"
        case BoolNe => s"($l != $r)"
        case BoolOr => s"($l or $r)"
        case BoolAnd => s"($l and $r)"

        // Int
        case IntAdd  => wrapI32(s"$l + $r")
        case IntSub  => wrapI32(s"$l - $r")
        case IntMul  => wrapI32(s"$l * $r")
        case IntDiv  => wrapI32(s"$l // $r")   // TODO: trunc semantics
        case IntMod  => wrapI32(s"$l % $r")    // TODO: sign semantics
        case IntOr   => wrapI32(s"$l | $r")
        case IntAnd  => wrapI32(s"$l & $r")
        case IntXor  => wrapI32(s"$l ^ $r")
        case IntShl  => wrapI32(s"$l << $r")
        case IntShr  => wrapI32(s"$l >> $r")
        case IntUShr => wrapI32(s"($l & 0xFFFFFFFF) >> $r")
        case IntEq   => s"($l == $r)"
        case IntNe   => s"($l != $r)"
        case IntLt   => s"($l < $r)"
        case IntLe   => s"($l <= $r)"
        case IntGt   => s"($l > $r)"
        case IntGe   => s"($l >= $r)"
        case IntUDiv | IntURem | IntULt | IntULe | IntUGt | IntUGe =>
          s"None  # TODO IntUnsigned: $l, $r"

        // Long
        case LongAdd  => wrapI64(s"$l + $r")
        case LongSub  => wrapI64(s"$l - $r")
        case LongMul  => wrapI64(s"$l * $r")
        case LongDiv  => wrapI64(s"$l // $r")
        case LongMod  => wrapI64(s"$l % $r")
        case LongOr   => wrapI64(s"$l | $r")
        case LongAnd  => wrapI64(s"$l & $r")
        case LongXor  => wrapI64(s"$l ^ $r")
        case LongShl  => wrapI64(s"$l << $r")
        case LongShr  => wrapI64(s"$l >> $r")
        case LongUShr => wrapI64(s"($l & 0xFFFFFFFFFFFFFFFF) >> $r")
        case LongEq   => s"($l == $r)"
        case LongNe   => s"($l != $r)"
        case LongLt   => s"($l < $r)"
        case LongLe   => s"($l <= $r)"
        case LongGt   => s"($l > $r)"
        case LongGe   => s"($l >= $r)"
        case LongUDiv | LongURem | LongULt | LongULe | LongUGt | LongUGe =>
          s"None  # TODO LongUnsigned: $l, $r"

        // Float
        case FloatAdd => wrapF32(s"$l + $r")
        case FloatSub => wrapF32(s"$l - $r")
        case FloatMul => wrapF32(s"$l * $r")
        case FloatDiv => wrapF32(s"$l / $r")
        case FloatMod => wrapF32(s"$l % $r")
        case FloatEq => s"($l == $r)"
        case FloatNe => s"($l != $r)"
        case FloatLt => s"($l < $r)"
        case FloatLe => s"($l <= $r)"
        case FloatGt => s"($l > $r)"
        case FloatGe => s"($l >= $r)"

        // Double
        case DoubleAdd => s"($l + $r)"
        case DoubleSub => s"($l - $r)"
        case DoubleMul => s"($l * $r)"
        case DoubleDiv => s"($l / $r)"
        case DoubleMod => s"($l % $r)"
        case DoubleEq => s"($l == $r)"
        case DoubleNe => s"($l != $r)"
        case DoubleLt => s"($l < $r)"
        case DoubleLe => s"($l <= $r)"
        case DoubleGt => s"($l > $r)"
        case DoubleGe => s"($l >= $r)"

        // String
        case StringConcat => s"($l + $r)"
        case StringCharAt => s"ord($l[$r])"
        case StringEq => s"($l == $r)"

        // Identity
        case RefEq => s"($l is $r)"
        case RefNe => s"($l is not $r)"

        // Class
        case ClassIsInstance       => s"isinstance($r, $l)"
        case ClassIsAssignableFrom => s"issubclass($r, $l)"
        case ClassCast             => r
        case ClassNewArray         => s"([None] * $r)"

    // -- Numeric wrapping helpers --------------------------------

    private def wrapI32(inner: String): String = s"${Prefix}i32($inner)"
    private def wrapI64(inner: String): String = s"${Prefix}i64($inner)"
    private def wrapF32(inner: String): String = s"${Prefix}f32($inner)"

    // -- Module singleton init -----------------------------------

    private def emitModuleSingletonInit(cls: PyClassDef): Unit =
      val modVar = moduleVarName(cls.name)
      val clsId  = classIdentifier(cls.name)
      line(s"$modVar = $clsId()")

    // -- Main guard ----------------------------------------------

    private def emitMainGuard(mainEntry: MainEntry, classes: List[PyClassDef]): Unit =
      val (mainClass, kind) = mainEntry
      val methodOpt = classes.find(_.name == mainClass).flatMap { cls =>
        cls.methods.find(_.name.simple.name == "main")
      }
      methodOpt.foreach { m =>
        val encoded = m.name.encoded
        val argsStr = if m.args.nonEmpty then "sys.argv[1:]" else ""
        val receiver = kind match
          case PyClassKind.ModuleClass => moduleVarName(mainClass)
          case _                       => classIdentifier(mainClass)
        line("import sys")
        line("if __name__ == \"__main__\":")
        indent()
        line(s"$receiver.$encoded($argsStr)")
        dedent()
      }

    // -- Name helpers --------------------------------------------

    /** Python identifier used for a Scala class (simple name, sanitized). */
    private def classIdentifier(cn: PyClassName): String =
      sanitizeIdent(cn.simpleName)

    /** Python variable holding the singleton of a Scala `object`.
     *  Uses the full qualified path so two modules with the same
     *  simple name in different packages don't collide. */
    private def moduleVarName(cn: PyClassName): String =
      s"${Prefix}mod_${cn.segments.map(sanitizeIdent).mkString("_")}_"

    /** Replace `$` with `_`, escape Python keywords. */
    private def sanitizeIdent(s: String): String =
      val cleaned = s.replace('$', '_')
      if PyIRRuntime.PythonKeywords.contains(cleaned) then cleaned + "_"
      else cleaned

    // -- Block flattening ----------------------------------------

    private def flattenBlock(tree: PyTree): List[PyTree] = tree match
      case PyBlock(stats, expr) =>
        stats.flatMap(flattenBlock) ::: flattenBlock(expr)
      case _: PyUnitLit => Nil
      case PySkip()     => Nil
      case _            => List(tree)

    // -- String escaping (control-character safe) ----------------

    private def escapeString(s: String): String =
      val sb = new StringBuilder(s.length + 8)
      var i = 0
      while i < s.length do
        val ch = s.charAt(i)
        ch match
          case '\\' => sb.append("\\\\")
          case '"'  => sb.append("\\\"")
          case '\n' => sb.append("\\n")
          case '\r' => sb.append("\\r")
          case '\t' => sb.append("\\t")
          case '\b' => sb.append("\\b")
          case '\f' => sb.append("\\f")
          case c if c < 0x20 || c == 0x7f =>
            sb.append("\\x%02x".format(c.toInt))
          case c if c > 0x7f =>
            sb.append("\\u%04x".format(c.toInt))
          case c =>
            sb.append(c)
        i += 1
      sb.toString

    // -- Numeric literal formatting (NaN/Inf safe) ---------------

    private def formatFloat(v: Float): String =
      if java.lang.Float.isNaN(v) then "float('nan')"
      else if v == Float.PositiveInfinity then "float('inf')"
      else if v == Float.NegativeInfinity then "float('-inf')"
      else v.toString

    private def formatDouble(v: Double): String =
      if java.lang.Double.isNaN(v) then "float('nan')"
      else if v == Double.PositiveInfinity then "float('inf')"
      else if v == Double.NegativeInfinity then "float('-inf')"
      else v.toString
