@main def javalibLangStringBasic(): Unit =
  println("length:" + "hello".length())
  println("charat:" + "Scala".charAt(2).toInt)
  println("substring:" + "scala".substring(2) + ":" + "scala".substring(1, 4))
  println("subseq:" + "scala".subSequence(1, 4))
  println("concat:" + "foo".concat("bar"))
  println("equals:" + "abc".equals("abc") + ":" + "abc".equals(java.lang.Integer.valueOf(1)))
  println("compare:" + "abc".compareTo("abd") + ":" + "AbC".compareToIgnoreCase("aBc"))
  println("contains:" + "marker".contains("ark"))
  println("starts:" + "scalapy".startsWith("ala", 2) + ":" + "scalapy".startsWith("scala"))
  println("ends:" + "scalapy".endsWith("py"))
  println("index-str:" + "banana".indexOf("na") + ":" + "banana".indexOf("na", 3) + ":" + "banana".lastIndexOf("na") + ":" + "banana".lastIndexOf("na", 3))
  println("index-char:" + "banana".indexOf('a') + ":" + "banana".indexOf('a', 2) + ":" + "banana".lastIndexOf('a') + ":" + "banana".lastIndexOf('a', 4))
  println("strip:[" + "\t  hi \n".trim() + "]:[" + "  hi  ".strip() + "]:[" + "  hi  ".stripLeading() + "]:[" + "  hi  ".stripTrailing() + "]")
  println("blank:" + "".isBlank() + ":" + "  \t".isBlank() + ":" + " x ".isBlank())
  println("case:" + "ScAlA".toLowerCase() + ":" + "ScAlA".toUpperCase())
  println("repeat:" + "ab".repeat(3))
  println("codepoint:" + "scala".codePointAt(2) + ":" + "scala".codePointBefore(2) + ":" + "scala".codePointCount(1, 4) + ":" + "scala".offsetByCodePoints(1, 3))
  println("region:" + "ScalaPy".regionMatches(1, "Xcal", 1, 3) + ":" + "ScalaPy".regionMatches(true, 0, "scala", 0, 5))
  println("replace:" + "banana".replace('a', 'o') + ":" + "banana".replace("na", "NO"))
  println("hash:" + "abc".hashCode())
  val chars = "Az".toCharArray()
  println("chararray:" + chars.length + ":" + chars(0).toInt + ":" + chars(1).toInt)
  val copied = new Array[Char](3)
  "scala".getChars(1, 4, copied, 0)
  println("getchars:" + copied(0).toInt + ":" + copied(1).toInt + ":" + copied(2).toInt)
  println("indent:[" + "a\nb".indent(2).replace('\n', '|') + "]")
  println("stripindent:[" + "  a\n    b\n".stripIndent().replace('\n', '|') + "]")
  println("escapes:[" + "\\n\\141".translateEscapes().replace('\n', '|') + "]")
