@main def javalibLangStringCtors(): Unit =
  val chars = Array[Char]('s', 'c', 'a', 'l', 'a')
  println("chars:" + new String(chars))
  println("chars-slice:" + new String(chars, 1, 3))
  val codePoints = Array[Int](65, 0x1F600, 66)
  println("codepoints:" + new String(codePoints, 0, 3))
  println("copy:" + new String("copy-me"))
  val utf8 = "Grüezi".getBytes()
  println("utf8:" + new String(utf8))
  println("utf8-name:" + new String(utf8, "UTF-8"))
  val ascii = Array[scala.Byte](65.toByte, 66.toByte, 67.toByte, 68.toByte)
  println("slice:" + new String(ascii, 1, 2))
  println("slice-name:" + new String(ascii, 1, 2, "US-ASCII"))
  val asciiBytes = "AB".getBytes("US-ASCII")
  println("bytes:" + asciiBytes.length + ":" + asciiBytes(0) + ":" + asciiBytes(1))
  val builder = new java.lang.StringBuilder().append("from").append('-').append("builder")
  println("from-builder:" + new String(builder))
  val buffer = new java.lang.StringBuffer("from").append('-').append("buffer")
  println("from-buffer:" + new String(buffer))
