package dotty.tools.backend.python

import dotty.tools.backend.python.ir.pyir.*

import org.junit.Assert.*
import org.junit.Test

/** Regression tests for encoder/codegen edge cases identified by Wave 6
 *  item 07 — empty-package top-level definitions whose lambdas are
 *  hoisted by `LambdaLift` onto a synthetic `Foo$package$`-shaped module
 *  class.
 *
 *  Both fixtures (`tests/run/Parser.scala`,
 *  `tests/run/for-desugar-strawman.scala`) failed with linker / runtime
 *  errors that pivoted on how the codegen lowered receivers for
 *  `JavaStatic`-flagged anonfuns whose owner is a module class:
 *
 *  - 07.1: `Select(This(emptyPkg), liftedAnonfun)` lowered the receiver
 *    via the package-class encoder, producing
 *    `loadModule(_lessempty_greater)` which the linker rejects.
 *
 *  - 07.2: a same-class call from inside another `staticmethod` body
 *    lowered the receiver to `PyThis()` (because
 *    `moduleClass == currentClassSym`) but `staticmethod` has no
 *    `self`, so Python raised `NameError` at runtime.
 *
 *  The integration coverage is the pair of `tests/run` fixtures
 *  themselves; this file pins the IR-level invariant the linker checks
 *  so a regression in the receiver-anchoring contract is caught even
 *  before the support jars are rebuilt. The contract: every call against
 *  a module-class member that survives the codegen must reference a
 *  `PyClassName` the linker can resolve to a real `PyClassDef` (i.e.
 *  never the empty package's encoded name and never `self` from a
 *  static method).
 */
class PyEncoderEdgesTest:

  private val NoPos = PyPosition.NoPosition

  // ----------------------------------------------------------------
  // Helpers (mirrors PyStaticDispatchTest)
  // ----------------------------------------------------------------

  private def className(name: String): PyClassName = PyClassName(name)

  private def methodName(
      simple:    String,
      paramRefs: List[PyTypeRef] = Nil,
      resultRef: PyTypeRef       = PyPrimRef.VoidRef
  ): PyMethodName =
    PyMethodName(PySimpleMethodName(simple), paramRefs, resultRef)

  private def ctor(): PyMethodDef =
    PyMethodDef(
      flags        = PyMemberFlags.empty.withNamespace(PyMemberNamespace.Constructor),
      name         = PyMethodName(PySimpleMethodName.Constructor, Nil, PyPrimRef.VoidRef),
      originalName = PyOriginalName.NoOriginalName,
      args         = Nil,
      resultType   = PyVoidType,
      body         = Some(PySkip()(NoPos)),
      pos          = NoPos
    )

  private def method(
      name:       PyMethodName,
      args:       List[PyParamDef]  = Nil,
      body:       PyTree            = PySkip()(NoPos),
      resultType: PyType            = PyVoidType,
      namespace:  PyMemberNamespace = PyMemberNamespace.Public
  ): PyMethodDef =
    PyMethodDef(
      flags        = PyMemberFlags.empty.withNamespace(namespace),
      name         = name,
      originalName = PyOriginalName.NoOriginalName,
      args         = args,
      resultType   = resultType,
      body         = Some(body),
      pos          = NoPos
    )

  private def classDef(
      name:    PyClassName,
      methods: List[PyMethodDef],
      kind:    PyClassKind = PyClassKind.Class
  ): PyClassDef =
    PyClassDef(
      name         = name,
      originalName = PyOriginalName.NoOriginalName,
      kind         = kind,
      superClass   = None,
      interfaces   = Nil,
      fields       = Nil,
      methods      = methods,
      pos          = NoPos
    )

  // ----------------------------------------------------------------
  // 07.1 — Parser.scala: receiver re-anchor for hoisted JavaStatic
  // ----------------------------------------------------------------

  /** When the codegen produces a `PyApply` against an anonfun on a
   *  module-class owner, the receiver MUST be a `PyLoadModule` of that
   *  module class (or `PyThis()` when the call site lives in the same
   *  module class and is not in a static context). It MUST NOT be a
   *  `PyLoadModule` of the empty package — `_lessempty_greater` is the
   *  encoded name of the empty package class (`<empty>`'s
   *  `$lessempty$greater` mangling, post `$ → _`). The linker doesn't
   *  bundle a class by that name.
   *
   *  This test pins the well-formedness shape: a call generated by the
   *  fixed codegen for the `Parser$package$` lambda, when emitted to
   *  Python, must reference the actual module (`Parser_package_`) — the
   *  same name the corresponding `PyClassDef` carries. */
  @Test def lambdaCallReferencesModuleNotEmptyPackage(): Unit =
    val moduleName  = className("Parser_package_")
    val lambdaName  = methodName(
      "Parser_package_____strToToken_lzyINIT1__anonfun_1",
      List(PyClassRef(PyClassName.StringClass)),
      PyClassRef(className("Parser"))
    )
    // The lambda definition lives on the module class as a regular
    // (demoted) instance method.
    val lambdaDef = method(
      name       = lambdaName,
      args       = List(PyParamDef(
        name         = PyLocalName("__3"),
        originalName = PyOriginalName.NoOriginalName,
        ptpe         = PyStringType,
        mutable      = false,
        pos          = NoPos
      )),
      body       = PyNullLit()(NoPos),
      resultType = PyClassType(className("Parser")),
      namespace  = PyMemberNamespace.Public
    )
    val moduleClass = classDef(
      name    = moduleName,
      methods = List(ctor(), lambdaDef),
      kind    = PyClassKind.ModuleClass
    )
    // The SAM anon-class call site: receiver is `PyLoadModule(moduleName)`,
    // dispatching to the lambda by its encoded name.
    val callerBody = PyApply(
      flags     = PyApplyFlags.empty,
      receiver  = PyLoadModule(moduleName)(NoPos),
      className = moduleName,
      method    = lambdaName,
      args      = List(PyVarRef(PyLocalName("__3"))(PyStringType, NoPos))
    )(PyClassType(className("Parser")), NoPos)
    val callerMethod = method(
      name       = methodName(
        "apply",
        List(PyClassRef(PyClassName.StringClass)),
        PyClassRef(className("Parser"))
      ),
      args       = List(PyParamDef(
        name         = PyLocalName("__3"),
        originalName = PyOriginalName.NoOriginalName,
        ptpe         = PyStringType,
        mutable      = false,
        pos          = NoPos
      )),
      body       = callerBody,
      resultType = PyClassType(className("Parser"))
    )
    val samClass = classDef(
      name    = className("Parser_package__anon_1"),
      methods = List(ctor(), callerMethod)
    )
    // Stub Parser class so the encoded result type resolves.
    val parserStub = classDef(name = className("Parser"), methods = List(ctor()))

    val src = PyIREmitter.emitToString(List(parserStub, moduleClass, samClass), None)

    assertTrue(
      s"expected the SAM call site to reference `Parser_package_`:\n$src",
      src.contains("Parser_package_")
    )
    // The empty-package encoded name must never appear — every call to
    // a module-class member must resolve through the actual module's
    // encoded name.
    assertFalse(
      s"empty-package encoded name `_lessempty_greater` must not appear:\n$src",
      src.contains("_lessempty_greater")
    )

  // ----------------------------------------------------------------
  // 07.2 — for-desugar-strawman.scala: static-context same-class call
  //         must not lower to `self.method`
  // ----------------------------------------------------------------

  /** A `staticmethod`'s body that calls a sibling member on the same
   *  module class MUST NOT receive `self` — Python's `staticmethod`
   *  binds no `self`, and `self.method(...)` raises `NameError` at
   *  runtime. The fixed codegen routes the receiver through
   *  `PyLoadModule(currentClassSym)` instead.
   *
   *  This test pins the IR shape: a `PyApply` whose receiver is
   *  `PyLoadModule(selfModule)` (not `PyThis`) emitted from inside
   *  a `PublicStatic` method's body. */
  @Test def staticBodySameClassCallUsesLoadModule(): Unit =
    val moduleName = className("for_minusdesugar_minusstrawman_package_")
    val targetMethod = methodName(
      "Test__anonfun_4",
      List(PyClassRef(className("scala.collection.immutable.List")), PyPrimRef.IntRef),
      PyClassRef(className("scala.Option"))
    )
    val targetDef = method(
      name       = targetMethod,
      args       = List(
        PyParamDef(
          name         = PyLocalName("xs_1"),
          originalName = PyOriginalName.NoOriginalName,
          ptpe         = PyClassType(className("scala.collection.immutable.List")),
          mutable      = false,
          pos          = NoPos
        ),
        PyParamDef(
          name         = PyLocalName("x"),
          originalName = PyOriginalName.NoOriginalName,
          ptpe         = PyIntType,
          mutable      = false,
          pos          = NoPos
        )
      ),
      body       = PyNullLit()(NoPos),
      resultType = PyClassType(className("scala.Option")),
      namespace  = PyMemberNamespace.Public
    )
    // The static caller lives on the SAME module class. Its body must
    // reference `loadModule(<self>)`, not `self.target(...)`.
    val staticCallerName = methodName(
      "Test__anonfun_adapted_2",
      List(PyClassRef(className("scala.collection.immutable.List")), PyClassRef(PyClassName.ObjectClass)),
      PyClassRef(className("scala.Option"))
    )
    val callerArgs = List(
      PyVarRef(PyLocalName("xs_2"))(PyClassType(className("scala.collection.immutable.List")), NoPos),
      PyVarRef(PyLocalName("x"))(PyIntType, NoPos)
    )
    val callerBody = PyApply(
      flags     = PyApplyFlags.empty,
      receiver  = PyLoadModule(moduleName)(NoPos),
      className = moduleName,
      method    = targetMethod,
      args      = callerArgs
    )(PyClassType(className("scala.Option")), NoPos)
    val staticCaller = method(
      name       = staticCallerName,
      args       = List(
        PyParamDef(
          name         = PyLocalName("xs_2"),
          originalName = PyOriginalName.NoOriginalName,
          ptpe         = PyClassType(className("scala.collection.immutable.List")),
          mutable      = false,
          pos          = NoPos
        ),
        PyParamDef(
          name         = PyLocalName("x"),
          originalName = PyOriginalName.NoOriginalName,
          ptpe         = PyClassType(PyClassName.ObjectClass),
          mutable      = false,
          pos          = NoPos
        )
      ),
      body       = callerBody,
      resultType = PyClassType(className("scala.Option")),
      namespace  = PyMemberNamespace.PrivateStatic
    )
    val moduleCls = classDef(
      name    = moduleName,
      methods = List(ctor(), targetDef, staticCaller),
      kind    = PyClassKind.ModuleClass
    )
    // Stubs so the linker-shape can resolve.
    val listStub   = classDef(className("scala.collection.immutable.List"), List(ctor()))
    val optionStub = classDef(className("scala.Option"), List(ctor()))

    val src = PyIREmitter.emitToString(List(listStub, optionStub, moduleCls), None)

    val lines = src.linesIterator.toIndexedSeq
    // Locate the static caller's def.
    val staticCallerDefIdx = lines.indexWhere(line =>
      line.contains("def Test__anonfun_adapted_2"))
    assertTrue(
      s"expected static caller def in emitted source:\n$src",
      staticCallerDefIdx >= 0
    )
    // The preceding non-blank line must be `@staticmethod`.
    var prev = staticCallerDefIdx - 1
    while prev >= 0 && lines(prev).trim.isEmpty do prev -= 1
    assertTrue(
      s"expected `@staticmethod` decorator on static caller:\n$src",
      prev >= 0 && lines(prev).trim == "@staticmethod"
    )
    // No `self.<target>(...)` reference — the static body must use
    // module dispatch (`<encoded-module>.<target>(...)`).
    assertFalse(
      s"static method body must not reference `self.Test__anonfun_4`:\n$src",
      src.contains("self.Test__anonfun_4")
    )

end PyEncoderEdgesTest
